general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0

    col.active_border = rgba(ffffff55) rgba(ffffff22) 90deg
    col.inactive_border = rgba(ffffff55) rgba(ffffff22) 90deg

    layout = master
    allow_tearing = false
}

decoration {
    rounding = 0
    rounding_power = 0

    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
        size = 4
        passes = 4
        vibrancy = 99
        brightness = 1.8
        contrast = 2
        noise = 0.7
        new_optimizations = true
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

master {
    new_status = master
}

gestures {
    gesture = 3, left, dispatcher, workspace, +1
    gesture = 3, right, dispatcher, workspace, -1
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
